version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: screentime
      POSTGRES_USER: screentime
      POSTGRES_PASSWORD: screentime
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://screentime:screentime@db:5432/screentime
      TZ: Asia/Tokyo
      HMAC_SECRET: ${HMAC_SECRET:-change-me}
      INGEST_TOKENS: ${INGEST_TOKENS:-role:participant:devtoken}
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "-m", "app.jobs.scheduler"]
    environment:
      DATABASE_URL: postgresql+psycopg2://screentime:screentime@db:5432/screentime
      TZ: Asia/Tokyo
    volumes:
      - ./backend:/app
    depends_on:
      - db

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE: http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - api
      - web

volumes:
  db_data:
