[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "screentime-backend"
version = "0.1.0"
description = "Screentime Dashboard Backend"
requires-python = ">=3.11"
dependencies = []
